# Generated by Django 3.2.21 on 2023-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_link_url_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='link_image'),
        ),
    ]
