# Generated by Django 3.2.21 on 2023-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='Enter a link of a website', max_length=100, unique=True),
        ),
    ]
